// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUOo5FWFn9qckIK5Sf7xYHA6YvLiR60MA',
    appId: '1:932909614033:web:01f1f5744243e3e6e216f0',
    messagingSenderId: '932909614033',
    projectId: 'soutenance3-217dd',
    authDomain: 'soutenance3-217dd.firebaseapp.com',
    storageBucket: 'soutenance3-217dd.appspot.com',
    measurementId: 'G-7YH6EQHD5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfy0dvoBus3wlFbqtNII2Z9ReCfFsGEJU',
    appId: '1:932909614033:android:bf0e94ba53564db3e216f0',
    messagingSenderId: '932909614033',
    projectId: 'soutenance3-217dd',
    storageBucket: 'soutenance3-217dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0uQA9Jhhr-NqJLZ-lzsAnX-NbAFyQo2Q',
    appId: '1:932909614033:ios:aaa2ca73b78f7e4ce216f0',
    messagingSenderId: '932909614033',
    projectId: 'soutenance3-217dd',
    storageBucket: 'soutenance3-217dd.appspot.com',
    iosBundleId: 'com.example.projetsout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0uQA9Jhhr-NqJLZ-lzsAnX-NbAFyQo2Q',
    appId: '1:932909614033:ios:aaa2ca73b78f7e4ce216f0',
    messagingSenderId: '932909614033',
    projectId: 'soutenance3-217dd',
    storageBucket: 'soutenance3-217dd.appspot.com',
    iosBundleId: 'com.example.projetsout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUOo5FWFn9qckIK5Sf7xYHA6YvLiR60MA',
    appId: '1:932909614033:web:a6987bda6d955b24e216f0',
    messagingSenderId: '932909614033',
    projectId: 'soutenance3-217dd',
    authDomain: 'soutenance3-217dd.firebaseapp.com',
    storageBucket: 'soutenance3-217dd.appspot.com',
    measurementId: 'G-PPR0DMXZ3L',
  );
}
